In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [26]:
%%bash
head sunspot.txt

 0       1     2     3     4     5     6     7     8     9     10   11     12
 1749   58.0  62.6  70.0  55.7  85.0  83.5  94.8  66.3  75.9  75.5 158.6  85.2
 1750   73.3  75.9  89.2  88.3  90.0 100.0  85.4 103.0  91.2  65.7  63.3  75.4
 1751   70.0  43.5  45.3  56.4  60.7  50.7  66.3  59.8  23.5  23.2  28.5  44.0
 1752   35.0  50.0  71.0  59.3  59.7  39.6  78.4  29.3  27.1  46.6  37.6  40.0
 1753   44.0  32.0  45.7  38.0  36.0  31.7  22.0  39.0  28.0  25.0  20.0   6.7
 1754    0.0   3.0   1.7  13.7  20.7  26.7  18.8  12.3   8.2  24.1  13.2   4.2
 1755   10.2  11.2   6.8   6.5   0.0   0.0   8.6   3.2  17.8  23.7   6.8  20.0
 1756   12.5   7.1   5.4   9.4  12.5  12.9   3.6   6.4  11.8  14.3  17.0   9.4
 1757   14.1  21.2  26.2  30.0  38.1  12.8  25.0  51.3  39.7  32.5  64.7  33.5


In [27]:
dados = np.loadtxt('sunspot.txt', usecols=range(1,13))

In [28]:
dados

array([[  1. ,   2. ,   3. , ...,  10. ,  11. ,  12. ],
       [ 58. ,  62.6,  70. , ...,  75.5, 158.6,  85.2],
       [ 73.3,  75.9,  89.2, ...,  65.7,  63.3,  75.4],
       ...,
       [ 58.3,  32.9,  64.3, ...,  53.3,  61.8,  40.8],
       [ 62.9,  38. ,  57.9, ...,  85.6,  77.6,  90.3],
       [ 81.8, 102.3,  91.9, ...,  60.6,  70.2,  76.7]])

## Criando conjunto de testes e de treino


In [39]:
K = 20 #Ver se isso tem a ver com o tamanha do K pastas
N = np.size(dados)
M = N-K #retira os dados de treino
X = np.empty((M,K))#cria um vetor vazio com os tamanhos de M e K para o eixo X
y = np.empty((M,1))#cria um vetor vazio com os tamanhos de M e 0 para y NAO SEI PORQUE

for i in range(M):
    for k in range(K):
        X[i][k] = dados.flatten()[(i+k) - (k + 1)]
        print('i - k: ', i, k)
    y[i][0] = (dados.flatten()[i+K])
    print('i: ', i)

TypeError: 'int' object is not subscriptable

In [52]:
np.set_printoptions(threshold=3000)
print(np.round(X))

[[ 77.   0.   0. ...  84.  95.  66.]
 [ 76.  76. 159. ...  44.  45.  56.]
 [ 61.  51.  66. ...  47.  38.  40.]
 ...
 [177. 177. 177. ... 109. 109. 109.]
 [109. 109. 109. ... 134. 134. 134.]
 [134. 134. 134. ... 145. 145. 145.]]


In [24]:
n_dados_teste = 5*12 #ultimos 5 anos
X_treino = np.array(X[:-n_dados_teste])

NameError: name 'X' is not defined

In [23]:
X_treino

NameError: name 'X_treino' is not defined